# Generated by Django 4.2.5 on 2023-09-23 08:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttitudeTowardsOtherAnimals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Отношение к другим животным',
                'verbose_name_plural': 'Отношения к другим животным',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Окрас животного',
                'verbose_name_plural': 'Окрас животных',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Пол животного',
                'verbose_name_plural': 'Пол животных',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialQualitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Особое качество',
                'verbose_name_plural': 'Особые качества',
            },
        ),
        migrations.CreateModel(
            name='Temperament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Темперамент животного',
                'verbose_name_plural': 'Темпераменты животных',
            },
        ),
        migrations.CreateModel(
            name='Wool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Шерсть животного',
                'verbose_name_plural': 'Шерсть животных',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Кличка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('isOwnerFound', models.BooleanField(default=False)),
                ('age', models.IntegerField(verbose_name='Возраст (месяцев)')),
                ('heightAtWithers', models.IntegerField(verbose_name='Высота в холке (см)')),
                ('attitudeTowardsOtherAnimals', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animalprofile.attitudetowardsotheranimals', verbose_name='Отношение к другим животным')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animalprofile.color', verbose_name='Цвет')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animalprofile.gender', verbose_name='Пол')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animalprofile.kind', verbose_name='Вид')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='userprofile.useraccount')),
                ('specialQualitie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animalprofile.specialqualitie', verbose_name='Особые качества')),
                ('temperament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animalprofile.temperament', verbose_name='Темперамент')),
                ('wool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animalprofile.wool', verbose_name='Шерсть')),
            ],
            options={
                'verbose_name': 'Профиль животного',
                'verbose_name_plural': 'Профили животных',
                'ordering': ['name'],
            },
        ),
    ]
