# Generated by Django 4.2.5 on 2023-10-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_useraccount_preferences'),
        ('animalprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='inFavorites',
            field=models.ManyToManyField(related_name='infavorites_animal_set', to='userprofile.useraccount'),
        ),
    ]
