# Generated by Django 4.2.5 on 2023-09-27 11:39

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Электронная почта')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='RU')),
                ('vk', models.URLField(null=True, verbose_name='ВКонтакте')),
                ('tg', models.URLField(null=True, verbose_name='Телеграм')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_owner_shelter',
            field=models.BooleanField(default=False, verbose_name='Представитель приюта?'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='preferences',
            field=models.CharField(max_length=255, null=True, verbose_name='Предпочтения'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.contact'),
        ),
    ]
