# Generated by Django 4.2.5 on 2023-09-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_contact_email_alter_contact_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='preferences',
            field=models.CharField(blank=True, max_length=255, verbose_name='Предпочтения'),
        ),
    ]
